id: DAFE3CC5A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:45:28+00:00'
last_modified: '2022-05-26T10:15:01.104099+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b5ae:
      image_group_id: I1PD95863
      title: བདག་བྱིན་གྱིས་བརླབ་པའི་རིམ་པ་རྣམ་པར་དབྱེ་བ།
      total_pages: 1634
      order: 18
      base_file: b5ae.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
